### ISSUE TITLE
Tender: Laptop Loan

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/Tenders#1]
Here's the first tender - let's just do this in a simple doc for now

**[Laptop Loan System](https://docs.google.com/document/d/1rky5tgtd2UbShHww_N3PPiQa7hUe8jV2h_M35oGyAyU/edit?usp=sharing)**

For help writing your bid, look at [the sample bid in the template doc](https://docs.google.com/document/d/1_ZYRPX4JnDdY1F_C1CVyq99YPuV33eDs1Lk5A0wOBOE/edit?usp=sharing)

### UPDATE: 

We will leave this tender open until 

OCTOBER 24 2023 23:00 UTC 

and then give our decision by 

OCTOBER 27 2023 23:00 UTC

### UPDATE

Finance informs that the winning contractor must have or purchase Professional Indemnity Insurance. Please itemise the cost on your bid and we will pay this before signing the contract.

**Comment by haroon-ali-dev** [comment]
Hi Sally. Here is my bid. Please let me know if anything needs to change or if something should be said differently etc.
Thanks.

# Qualified Supplier

## Declaration
I am a qualified supplier, and I am tendering for this work.
- I am a CYF-certified developer. I have graduated CYF Fundamentals.
- I have a minimum of 4 kyu on my [Codewars profile](https://www.codewars.com/users/haroon-ali-dev) and I am happy to walk through any kata on my profile on request.
- I have a portfolio website with at least two team and two solo projects. I have provided links.
- I have right to work in the UK which I can prove with an online share code.

## Portfolio
- [Portfolio website](https://haroon-ali-portfolio.vercel.app/)
- [Solo project 1](https://github.com/haroon-ali-dev/point-of-sale)
- [Solo project 2](https://github.com/haroon-ali-dev/google-maps-crm)
- [Team project 1](https://github.com/Miladepour/SyntaxSquad-Project-Kunji)
- [Team project 2](https://github.com/haroon-ali-dev/event-manager)

## Contact Details
- Name: Haroon Ali
- Email: haroon.ali.1104@gmail.com
- CV: [View](https://docs.google.com/document/d/1RdoTHMU6o7SDpyD36igBgygytLlTbbKw6sYC-uO1UmE/edit?usp=sharing)

# Proposal
This proposal outlines the development of a comprehensive solution to streamline and automate the management of laptop loan requests, approvals, and document handling. The system will leverage existing tools such as Airtable, Google Forms, Slack, Zapier, QR-ME, and Xodo Sign (formerly Eversign) to create an efficient and user-friendly workflow.

## Components

### 1. Airtable Database Setup
Set up an Airtable database with four tables: hardware, human, location, and value.

### 2. Google Forms Integration
Create a user-friendly Google Forms interface for submitting laptop loan requests.

### 3. Zapier Integration
- Connect Google Forms to the Airtable database using Zapier.
- When a form response is submitted, update the Airtable database with the user's request details.
- Post a notification message in a designated Slack channel to inform admins of the new request.

### 4. Admin Actions
- Admins can review and manage requests within the Airtable database.
- If a request is rejected, Zapier will automatically send an email notification to the requesting user.
- If a request is approved, the following actions will be triggered:
  - A QR code will be generated using Zapier and QR-ME.
  - Admins can access the QR code through the QR-ME dashboard.
  - A document template will be emailed to the user using Zapier and Xodo Sign (formerly Eversign) for signature.

### 5. Document Signing Workflow
- Once the user signs the document, the database will be updated to reflect the signed status.
- A Slack message will be posted in the designated channel to notify admins of the completed process.

### 6. Deadline Reminders
- Create a scheduled task in Zapier (running daily) to check for approaching document signing deadlines.
- Implement a custom script, if necessary, to analyze data in the database and send reminder emails to users with impending deadlines.

### 7. Data Migration:
- Import existing data from Google Sheets into the Airtable database, ensuring alignment with the Airtable schema.
- Perform necessary data transformations, export to CSV, and import into Airtable to ensure data continuity.

## Benefits
- Streamlined laptop request and approval process.
- Real-time notifications and automatic generation of QR codes.
- Automated document signing and tracking.
- User-friendly deadline reminders.
- Efficient data migration and management.

# Deliverables
- Professional Indemnity Insurance - £68.28/year -  `Before contract is signed`
- Setup and configure Airtable database - £180 - `22nd November 2023`
- Create and connect Google Forms to Zapier and Airtable - £50 - `24th November 2023`
- Connect Slack, Xodo Sign (formerly Eversign), Airtable and Zapier to complete automation. Add schedule for checking deadlines - £225 - `1st December 2023`
- Data import - £180 - `8th December 2023`
- Document the system - £100 - `15th December 2023`
- Train staff on the new system and record the training session (30min) - £50 - `22nd December 2023`
- Transition plan - £50 - `3rd January 2023`
- Six-month bonus - £100 - `1st July 2024`

# Considerations
- Zapier Starter plan. It seems some of the requirements require multi-step zaps. This is only available on the paid Zapier Starter plan so we might need that.
- QR-ME Premium plan. To generate a QR code automatically using QR-ME API, a premium plan is required. **Admins can manually generate QR codes using websites easily so maybe this cost can be completely avoided.**
- For sending emails, there is a 5/hour and 10/hour sending limit on free and paid Zapier plans respectively if using Email by Zapier. Might want to consider using SMTP by Zapier with SendGrid API (100 emails a day for free).

**Comment by haroon-ali-dev** [comment]
@SallyMcGrath Hi. It's been two weeks since this tender was posted. Can you please tell us how long it takes for bids to be selected? Thanks.

**Comment by Mohammedal-abdulhamid** [comment]
Hi Sally, here is my bid, please inform me if you need any further details 
### Declaration
I am a CYF-certified developer. I have graduated CYF Fundamentals.
I have a minimum of 4 kyu on my [CodeWar](https://www.codewars.com/users/Mohammedal-abdulhamid) and I am happy to walk through any kata on my profile on request.
I have a [portfolio](https://main--reliable-gaufre-e022a6.netlify.app/) website with at least two team and two solo projects. I have provided links.
I have right to work in the UK which I can prove with an online share code.
### Contact Details
Name : Mohammed Al-abdulhamid
Email : mohammedalabdulhamid@gmail.com
CV : [see my CV](https://docs.google.com/document/d/1pXDlgdrrawUbh-VtMUe5Nz_PjdH4u1PFEWyqJfcnMnQ/edit)

### Proposal

**Project Overview:**

Code Your Future (CYF) is seeking a solution to streamline its laptop management process. Currently, managing laptops for trainees is a time-consuming task, creating delays in starting new classes. To address this, CYF is looking to improve equipment management by enhancing efficiency, accountability, and transparency.

**Objectives:**

- Determine WHO possesses WHAT and WHERE it's located.
- Ensure all machine holders sign a loan agreement acknowledging responsibility.
- Allow trainees to provide sufficient notice when requiring a machine, with the deadline being two weeks before Fundamentals begins.

**Solution:**

We propose implementing an Equipment Management System that integrates Airtable, Zapier, Google Forms, Eversign, and Slack. The solution consists of the following components:

Airtable Database Setup (£180): We will set up and configure the Airtable database, creating tables for HARDWARE, HUMAN, LOCATION, and VALUE.

- Integration with Eversign, Zapier, Google Forms, and Slack (£225): we will integrate Airtable with Eversign for loan agreement signing, Zapier for automation, Google Forms for simplified user interaction, and Slack for automated notifications.
- 
- Google Forms Creation and Integration (£50): We will create user-friendly Google Forms to streamline the trainee request process and integrate them with Airtable for data management.
- 
- Data Import and Cleanup (£180): We will clean and import data from existing Google Sheets into the new Airtable structure, ensuring a smooth transition.
- 
- Documentation (£100): We will thoroughly document the entire system, including user guides and system architecture.
- 
- Staff Training (£50): We will train CYF staff on how to use the new system and provide a 30-minute recorded training session for future reference.
- 
- Transition Plan (£50): We will create a comprehensive transition plan for the project, ensuring a smooth handover to CYF's team.
- 
- Six-Month Bonus (£100): If the system remains in regular use at CYF six months after implementation, we will provide a bonus payment to acknowledge its ongoing value.
- 





**Project Timeline**:


- Set up and configure Airtable database: November 7th to November 14th (1 week)
- 
- Integrate Airtable with Eversign, Zapier, Google Forms, and Slack: November 15th to November 24th (1.5 weeks)
- 
- Create and connect Google Forms: November 25th to November 28th (4 days)
- 
- Data import - Clean and import data from existing Google Sheets: November 29th to December 6th (1 week)
- 
- Document the system: December 7th to December 16th (1.5 weeks)
- 
- Train staff on the new system and record the training session: December 17th to December 20th (4 days)
- 
- Transition plan: December 21st to December 23rd (3 days)

**Comment by SallyMcGrath** [comment]
# 🤝 Contract Awarded

I am awarding this contract to @haroon-ali-dev pending these amends:

1. Please schedule transition in the New Year so it doesn't get lost in the Christmas holidays

~ @SallyMcGrath 

## 👣 Next steps

1. Finalise your proposal with any amends.
2. Book a call with @SallyMcGrath, link in my Slack Profile

##  🎚️ Feedback

If your bid was unsuccessful and you would like private feedback, please write to sally@codeyourfuture.io and I will send it to you directly. Please include a link to your bid. And if you would like to help our community learn, please post that feedback in this thread! 

🎉 Thanks for the bids, everyone!
